#!/usr/bin/env python3
"""Generate a markdown view inventory for a SysML v2 package folder.

Scans every .sysml file under the given folder, extracts each declared
`view` block (viewpoint, framed concern, expose targets, depth, render
hint), and writes a human-readable index that maps each view to its
source file and the rendered artifact name used by the privileged Syside
validation workflow (`syside viz view`).

Self-contained: no dependency on the view editor package, so it runs on
any branch.

Usage:
    python scripts/generate_view_index.py \
        textual-notation-of-model/packages/features/middleware
"""
from __future__ import annotations

import re
import sys
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class ViewSpec:
    name: str
    viewpoint: str = ""
    viewpoint_type: str = ""
    concern: str = ""
    exposes: list[str] = field(default_factory=list)
    depth: str = ""
    render: str = ""


VIEW_RE = re.compile(r"\bview\s+([A-Za-z_][A-Za-z0-9_]*)\s*(?::\s*[A-Za-z_][A-Za-z0-9_]*)?\s*\{")
VIEWPOINT_RE = re.compile(
    r"viewpoint\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*([A-Za-z_][A-Za-z0-9_]*)\s*\{"
)
FRAME_RE = re.compile(r"frame\s+([A-Za-z_][A-Za-z0-9_.]*)")
EXPOSE_RE = re.compile(r"expose\s+([A-Za-z_][A-Za-z0-9_.:*]*)")
DEPTH_RE = re.compile(r"attribute\s+depth\s*=\s*(-?\d+)")
RENDER_RE = re.compile(r"render\s+([A-Za-z_][A-Za-z0-9_]*)")


def _strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"//[^\n]*", "", text)
    return text


def _find_block(text: str, decl: str, name: str) -> str | None:
    match = re.search(rf"\b{decl}\s+{name}\b[^{{]*\{{", text)
    if not match:
        return None
    start = match.end() - 1
    depth = 1
    for i in range(start + 1, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[match.start() : i + 1]
    return None


def parse_view_spec(model_text: str, name: str) -> ViewSpec | None:
    block = _find_block(_strip_comments(model_text), "view", name)
    if not block:
        return None
    spec = ViewSpec(name=name)
    vp = VIEWPOINT_RE.search(block)
    if vp:
        spec.viewpoint, spec.viewpoint_type = vp.group(1), vp.group(2)
    frame = FRAME_RE.search(block)
    if frame:
        spec.concern = frame.group(1)
    spec.exposes = [e for e in EXPOSE_RE.findall(block) if e != name]
    depth = DEPTH_RE.search(block)
    if depth:
        spec.depth = depth.group(1)
    render = RENDER_RE.search(block)
    if render:
        spec.render = render.group(1)
    return spec


def collect_views(folder: Path) -> list[tuple[Path, list[ViewSpec]]]:
    out = []
    for path in sorted(folder.glob("*.sysml")):
        text = path.read_text(encoding="utf-8")
        views = []
        for match in VIEW_RE.finditer(text):
            name = match.group(1)
            spec = parse_view_spec(text, name)
            if spec is not None:
                views.append(spec)
        if views:
            out.append((path, views))
    return out


def render_markdown(folder: Path) -> str:
    collected = collect_views(folder)
    diagrams_dir = folder / "diagrams"
    lines = [
        "# Middleware Views",
        "",
        "This index lists every SysML v2 `view` declared in the `.sysml` files of",
        "this folder, with the diagram SysIDE renders from it (`syside viz view`,",
        "run by the Privileged Syside Validation workflow). The SVGs live in",
        "[`diagrams/`](diagrams/) beside the model files.",
        "",
        "Generated by `scripts/generate_view_index.py` — do not edit by hand.",
        "",
        f"**{len(collected)} files, "
        f"{sum(len(v) for _, v in collected)} views.**",
        "",
    ]
    for path, views in collected:
        lines.append(f"## `{path.name}`")
        lines.append("")
        for spec in views:
            lines.append(f"### `{spec.name}`")
            lines.append("")
            lines.append(f"- **Source:** `{path.name}`")
            if spec.viewpoint:
                lines.append(
                    f"- **Viewpoint:** `{spec.viewpoint}` (`{spec.viewpoint_type}`)"
                )
            if spec.concern:
                lines.append(f"- **Concern:** `{spec.concern}`")
            if spec.exposes:
                lines.append(
                    "- **Exposes:** " + ", ".join(f"`{e}`" for e in spec.exposes)
                )
            if spec.depth:
                lines.append(f"- **Depth:** `{spec.depth}`")
            if spec.render:
                lines.append(f"- **Render:** `{spec.render}`")
            lines.append("")
            svg = diagrams_dir / f"diagram-{spec.name}.svg"
            if svg.exists():
                lines.append(f"![{spec.name}](diagrams/diagram-{spec.name}.svg)")
            else:
                lines.append(f"_Diagram not present: `diagrams/diagram-{spec.name}.svg` "
                             f"(regenerate via the Privileged Syside Validation workflow)._")
            lines.append("")
    return "\n".join(lines)


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    folder = Path(sys.argv[1]).resolve()
    if not folder.is_dir():
        print(f"Not a folder: {folder}", file=sys.stderr)
        return 2
    output = folder / "VIEWS.md"
    output.write_text(render_markdown(folder), encoding="utf-8")
    print(f"wrote {output} ({len(output.read_text(encoding='utf-8').splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
