"""O4 definition-admission batch 2: governed projection + API profile for the
remaining retained identities.

Batch 2 makes every retained O4 register row that no other generated layer
projects (O2 chain / O3 13, definition batch 1, O2+, W4 vocabulary carriers)
model-projected, together with the ontology-mapped classes that are not O4
register rows (successor and scoped-assurance classes) and the owner-exposed
W6 successor predicates. It is a SEPARATE pair from batch 1
(``definition-projection.json`` / ``definition-profile.json`` stay byte-stable
in content), generated by the same generator script.

Every admitted row is backed by a model-resident home that the generator
locates and reads itself, fail-closed:

* ``owned-doc`` / ``named-doc`` — a definition declaration (``<kind> def``) or
  a package, and ONE directly owned Documentation (anonymous or named, selected
  by name + index). The reviewed definition is the parity oracle; the recomputed
  observation must be ``normalized-exact`` (cosmetic normalization only).
* ``vocabulary-role`` — a directly owned named comment
  ``comment <Name> about <targets> /* ... */`` of the owning package; every
  ``about`` target must be a live definition or named documentation of the
  same file. These rows have no authored definition text; the comment body is
  the model-owned vocabulary role and claim boundary.
* ``retirement-record`` — a directly owned ``SuccessorRetirementRecord`` usage
  of the relationship-successor package whose ``predicate`` equals the
  identity (deprecated aliases).

Successor rows additionally carry every directly owned
``SuccessorRelationRecord`` usage whose ``predicate`` equals the identity (set
equality with the manifest, fail-closed) plus the typed ends of each carrier
``connection def``. The ``hasRelevantEvidenceContract`` row carries the
owner-adopted type-lineage range discriminator: the kernel
``requirement def EvidenceContract`` and the exact specialization closure pins,
each verified to specialize ``EvidenceContract`` with a direct import of the
owning kernel package.

Contract fields the model does not structurally carry (relationship
domain/range of vocabulary-only predicates, kernel mapping kind of
native/external classes, serializer mechanics of the runtime-mapped
predicates) are reviewed manifest fields; tests lock them byte-for-byte to the
authored ontology until Wave C deletes it. They are labeled as such in every
generated row (``contract_source``); nothing is inferred from names.

Boundaries: generation reads ONLY the admission manifest, the governed model
files named by it and the accepted external-reference profile (for the
external-reference echo). No O1 artifact, no register and no authored
ontology is read here. No runtime module imports this machinery. Rows claim no
traversal proof and no API element identity; deprecated aliases never
translate an old signature into a broader successor contract.

Read-only and offline; never imported by the runtime.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

ADMISSION_PATH = "docs/method-conformance/o4/definition-admission-batch2.yaml"
PROJECTION_PATH = "docs/method-conformance/o4/definition-batch2-projection.json"
PROFILE_PATH = "docs/method-conformance/o4/definition-batch2-profile.json"
DESIGN_PATH = "docs/method-conformance/o4/definition-admission-batch2-design.md"
MODULE_PATH = "de4sdv/semantic/definition_projection_batch2.py"
GENERATOR_PATH = "scripts/generate_definition_projection.py"
AUTHORITY_INVENTORY_PATH = "de4sdv/semantic/authority_inventory.py"
PROJECTION_O2P_PATH = "de4sdv/semantic/projection_o2p.py"
EXTERNAL_REFERENCE_PROFILE_PATH = "docs/method-conformance/o4/external-reference-profile.yaml"

ADMISSION_SCHEMA = "de4sdv.o4-definition-admission-batch2/v1"
PROJECTION_SCHEMA = "de4sdv.o4-definition-batch2-projection/v1"
PROFILE_SCHEMA = "de4sdv.o4-definition-batch2-profile/v1"
SUCCESSOR_CONTRACT = "de4sdv.relationship-successor/v1"

WARNING = (
    "no traversal proof, no runtime read by this artifact, no API element "
    "identity, no authority retirement; deprecated aliases are documented "
    "names only"
)

SEMANTIC_KINDS = frozenset({"class", "relationship"})
ADMISSION_CLASSES = {
    "definition": "class",
    "relationship-vocabulary": "relationship",
    "relationship-runtime": "relationship",
    "external-reference": None,  # class or relationship
    "successor": "relationship",
    "deprecated-alias": "relationship",
}
BOUNDARIES = frozenset(
    {
        "none",
        "native-grounding",
        "external-content",
        "ple-no-configurator-authority",
        "historical-redesign",
    }
)
HOME_FORMS = frozenset({"owned-doc", "named-doc", "vocabulary-role", "retirement-record"})
ACCOUNTING = frozenset({"retained", "unregistered", "merged", "w6-successor"})
SUPPORT = {
    "definition": "vocabulary-only",
    "relationship-vocabulary": "vocabulary-only",
    "relationship-runtime": "runtime-mapped-candidate",
    "external-reference": "external",
    "successor": "runtime-mapped-candidate",
    "deprecated-alias": "deprecated-alias",
}

#: Declaration keyword -> representation class / API metaclass.
REPRESENTATION_CLASSES = {
    "part": "part-definition",
    "requirement": "requirement-definition",
    "item": "item-definition",
    "allocation": "allocation-definition",
    "enum": "enumeration-definition",
    "action": "action-definition",
    "connection": "connection-definition",
}
API_METACLASSES = {
    "part": "PartDefinition",
    "requirement": "RequirementDefinition",
    "item": "ItemDefinition",
    "allocation": "AllocationDefinition",
    "enum": "EnumerationDefinition",
    "action": "ActionDefinition",
    "connection": "ConnectionDefinition",
}
FORM_REPRESENTATION = {
    "package-doc": ("package-owned-definition-documentation", "Documentation"),
    "vocabulary-role": ("vocabulary-role-comment", "Comment"),
    "retirement-record": ("successor-retirement-record", "PartUsage"),
}
WITNESS_FORMS = {
    "owned-doc": "ownedRelationship -> OwningMembership -> Documentation (anonymous, owner-selected index)",
    "named-doc": "ownedRelationship -> OwningMembership -> Documentation (named, owner-selected index)",
    "vocabulary-role": "ownedRelationship -> OwningMembership -> Comment (named, annotating the about targets)",
    "retirement-record": "ownedRelationship -> FeatureMembership -> PartUsage : SuccessorRetirementRecord",
}
SUCCESSOR_RECORD_FIELDS = (
    "predicate",
    "carrier",
    "mechanism",
    "strength",
    "sourceClass",
    "targetClass",
    "sourceUsage",
    "targetUsage",
    "inverse",
)
RETIREMENT_RECORD_FIELDS = ("predicate", "reason")
VERSION_RECORD_FIELDS = ("version", "supersedes")
SUCCESSOR_FILE = "textual-notation-of-model/packages/methods/de4sdv/de4sdv_relationship_carriers.sysml"
SUCCESSOR_PACKAGE = "DE4SDV_RelationshipSuccessor"

_COMMON_KEYS = frozenset(
    {"identity", "semantic_kind", "admission_class", "register", "boundary", "home",
     "reviewed_definition", "gates", "forward_obligations"}
)
_CLASS_KEYS = frozenset({"grounding", "external_reference"})
_RELATIONSHIP_KEYS = frozenset(
    {"relation", "mechanics", "carrier", "range_discriminator", "successor",
     "alias", "external_reference"}
)
_HOME_KEYS = {
    "owned-doc": {"form", "file", "owner", "index"},
    "named-doc": {"form", "file", "owner", "name", "index"},
    "vocabulary-role": {"form", "file", "owner", "name", "about", "about_imports"},
    "retirement-record": {"form", "file", "owner", "name"},
}
_IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_DEF_OWNER = re.compile(r"^(?P<kind>[a-z]+) def (?P<name>[A-Za-z_][A-Za-z0-9_]*)$")
_PACKAGE_OWNER = re.compile(r"^package (?P<name>[A-Za-z_][A-Za-z0-9_]*)$")


class DefinitionBatch2Error(ValueError):
    """The batch-2 admission document or model home violates the governed contract."""


# ---------------------------------------------------------------------------
# Bounded lexical machinery (comment/quote-inert; not a SysML parser)
# ---------------------------------------------------------------------------


class _Source:
    """One model file: original text, a structure mask and its comment spans.

    The mask blanks comment interiors and both quoted-token forms (double
    quoted strings and single-quoted unrestricted names) with spaces, keeping
    offsets and newlines, so braces, semicolons or keywords inside comments or
    quoted tokens can never move a declaration boundary or supply code.
    """

    def __init__(self, relative: str, text: str) -> None:
        self.relative = relative
        self.text = text
        out: list[str] = []
        self.comments: list[tuple[int, int, str]] = []
        index = 0
        length = len(text)
        while index < length:
            if text.startswith("/*", index):
                end = text.find("*/", index + 2)
                if end == -1:
                    raise DefinitionBatch2Error(f"{relative}: unterminated comment")
                self.comments.append((index, end + 2, text[index + 2:end]))
                out.append("".join("\n" if c == "\n" else " " for c in text[index:end + 2]))
                index = end + 2
                continue
            if text.startswith("//", index):
                end = text.find("\n", index)
                end = length if end == -1 else end
                out.append(" " * (end - index))
                index = end
                continue
            char = text[index]
            if char in ('"', "'"):
                start = index
                index += 1
                while index < length:
                    if text[index] == "\\":
                        index += 2
                    elif text[index] == char:
                        index += 1
                        break
                    else:
                        index += 1
                else:
                    raise DefinitionBatch2Error(f"{relative}: unterminated quoted token")
                out.append(char + " " * (index - start - 2) + char)
                continue
            out.append(char)
            index += 1
        self.mask = "".join(out)
        depth = 0
        self.depth: list[int] = []
        for char in self.mask:
            self.depth.append(depth)
            depth += (char == "{") - (char == "}")
        if depth != 0:
            raise DefinitionBatch2Error(f"{relative}: unbalanced braces")

    # -- blocks ------------------------------------------------------------
    def _braced(self, header_end: int, label: str) -> tuple[int, int]:
        index = header_end
        while index < len(self.mask) and self.mask[index] not in "{;":
            index += 1
        if index >= len(self.mask) or self.mask[index] == ";":
            raise DefinitionBatch2Error(f"{self.relative}: {label} has no owned body")
        open_index = index
        target = self.depth[open_index]
        for close in range(open_index + 1, len(self.mask)):
            if self.mask[close] == "}" and self.depth[close] == target + 1:
                return open_index, close
        raise DefinitionBatch2Error(f"{self.relative}: {label} body is unterminated")

    def _unique(self, pattern: str, label: str, span: tuple[int, int] | None = None,
                direct: bool = False) -> re.Match[str]:
        start, end = span if span else (0, len(self.mask))
        base = self.depth[start] + 1 if span else 0
        matches = [
            match for match in re.finditer(pattern, self.mask[start:end])
            if not direct or self.depth[start + match.start()] == base
        ]
        if not matches:
            raise DefinitionBatch2Error(f"{self.relative}: {label} not found")
        if len(matches) > 1:
            raise DefinitionBatch2Error(f"{self.relative}: {label} is ambiguous ({len(matches)} live matches)")
        return matches[0]

    def owner_block(self, owner: str) -> tuple[int, int]:
        """Exactly one live ``package X`` or ``<kind> def X`` block."""
        package = _PACKAGE_OWNER.match(owner)
        if package:
            pattern = r"\bpackage\s+" + re.escape(package["name"]) + r"(?=\s*\{)"
        else:
            definition = _DEF_OWNER.match(owner)
            if not definition:
                raise DefinitionBatch2Error(f"{self.relative}: unsupported owner form {owner!r}")
            pattern = (r"(?m)^[ \t]*(?:(?:public|private|protected)\s+)?(?:abstract\s+)?"
                       + re.escape(definition["kind"]) + r"\s+def\s+"
                       + re.escape(definition["name"]) + r"\b")
        match = self._unique(pattern, owner)
        return self._braced(match.end(), owner)

    def defines(self, name: str) -> bool:
        return re.search(r"\bdef\s+" + re.escape(name) + r"\b", self.mask) is not None

    def names_documentation(self, name: str) -> bool:
        return re.search(r"\bdoc\s+" + re.escape(name) + r"\b", self.mask) is not None

    # -- annotations ---------------------------------------------------------
    def direct_annotations(self, block: tuple[int, int]) -> list[dict[str, Any]]:
        """Documentation and named comments at the block body's direct depth."""
        open_index, close = block
        base = self.depth[open_index] + 1
        found: list[dict[str, Any]] = []
        previous_end = open_index + 1
        for start, end, body in self.comments:
            if start <= open_index or end > close:
                continue
            if self.depth[start] != base:
                previous_end = max(previous_end, end)
                continue
            segment = self.mask[previous_end:start]
            cut = max(segment.rfind(";"), segment.rfind("{"), segment.rfind("}"))
            prefix = " ".join(segment[cut + 1:].split())
            previous_end = end
            doc = re.fullmatch(r"(?:(?:public|private|protected)\s+)?doc(?:\s+([A-Za-z_]\w*))?", prefix)
            if doc:
                found.append({"kind": "doc", "name": doc[1], "about": None, "body": body})
                continue
            comment = re.fullmatch(
                r"(?:(?:public|private|protected)\s+)?comment\s+(?!about\b)([A-Za-z_]\w*)"
                r"(?:\s+about\s+(.+))?",
                prefix,
            )
            if comment:
                about = [item.strip() for item in comment[2].split(",")] if comment[2] else []
                found.append({"kind": "comment", "name": comment[1], "about": about, "body": body})
        return found

    # -- records -------------------------------------------------------------
    def direct_record_usages(self, block: tuple[int, int], record_type: str) -> dict[str, tuple[int, int]]:
        open_index, close = block
        base = self.depth[open_index] + 1
        usages: dict[str, tuple[int, int]] = {}
        pattern = r"\bpart\s+([A-Za-z_]\w*)\s*:\s*" + re.escape(record_type) + r"\s*(?=\{)"
        for match in re.finditer(pattern, self.mask[open_index:close]):
            position = open_index + match.start()
            if self.depth[position] != base:
                continue
            name = match[1]
            if name in usages:
                raise DefinitionBatch2Error(f"{self.relative}: duplicate record usage {name!r}")
            usages[name] = self._braced(open_index + match.end(), f"record {name}")
        return usages

    def record_fields(self, block: tuple[int, int], fields: tuple[str, ...], label: str) -> dict[str, str]:
        open_index, close = block
        base = self.depth[open_index] + 1
        values: dict[str, str] = {}
        for match in re.finditer(r"\battribute\s*:>>\s*([A-Za-z_]\w*)\s*=\s*", self.mask[open_index:close]):
            position = open_index + match.start()
            if self.depth[position] != base:
                continue
            key = match[1]
            value_start = open_index + match.end()
            if self.text[value_start:value_start + 1] != '"':
                raise DefinitionBatch2Error(f"{self.relative}: {label}.{key} is not a String literal")
            value_end = value_start + 1
            while self.text[value_end] != '"':
                value_end += 2 if self.text[value_end] == "\\" else 1
            rest = self.mask[value_end + 1:close].lstrip()
            if not rest.startswith(";"):
                raise DefinitionBatch2Error(f"{self.relative}: {label}.{key} is not a single literal")
            if key in values:
                raise DefinitionBatch2Error(f"{self.relative}: {label}.{key} is assigned twice")
            values[key] = self.text[value_start + 1:value_end]
        if set(values) != set(fields):
            raise DefinitionBatch2Error(
                f"{self.relative}: {label} fields {sorted(values)} != {sorted(fields)}"
            )
        return values

    def carrier_ends(self, declaration: str) -> list[dict[str, str]]:
        block = self.owner_block(declaration)
        open_index, close = block
        base = self.depth[open_index] + 1
        ends = []
        for match in re.finditer(r"\bend\s+([A-Za-z_]\w*)\s*:\s*([A-Za-z_][\w:]*)\s*;", self.mask[open_index:close]):
            if self.depth[open_index + match.start()] == base:
                ends.append({"name": match[1], "type": match[2]})
        if len(ends) != 2:
            raise DefinitionBatch2Error(f"{self.relative}: {declaration} must own exactly two typed ends")
        return ends

    def specializes(self, declaration: str, target: str) -> bool:
        definition = _DEF_OWNER.match(declaration)
        if not definition:
            return False
        pattern = (r"(?m)^[ \t]*(?:(?:public|private|protected)\s+)?(?:abstract\s+)?"
                   + re.escape(definition["kind"]) + r"\s+def\s+"
                   + re.escape(definition["name"]) + r"\b")
        match = self._unique(pattern, declaration)
        header_end = match.end()
        while header_end < len(self.mask) and self.mask[header_end] not in "{;":
            header_end += 1
        header = self.mask[match.end():header_end]
        special = re.match(r"\s*(?::>|\bspecializes\b)\s*(.+)$", header, re.S)
        if not special:
            return False
        names = {item.strip().split("::")[-1] for item in special[1].split(",")}
        return target in names


def clean_body(body: str) -> str:
    """Cosmetic only: drop leading comment-continuation stars, collapse spaces."""
    lines = [re.sub(r"^\s*\*\s?", "", line) for line in body.splitlines()]
    return " ".join(" ".join(lines).split())


# ---------------------------------------------------------------------------
# Manifest
# ---------------------------------------------------------------------------


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise DefinitionBatch2Error(message)


def _nonempty(value: Any) -> bool:
    return isinstance(value, str) and bool(value.strip()) and value == value.strip()


def _validate_home(identity: str, home: Any) -> None:
    _require(isinstance(home, dict), f"{identity}: home must be a mapping")
    form = home.get("form")
    _require(form in HOME_FORMS, f"{identity}: home.form must be one of {sorted(HOME_FORMS)}")
    _require(set(home) == _HOME_KEYS[form],
             f"{identity}: home keys {sorted(home)} != {sorted(_HOME_KEYS[form])}")
    _require(_nonempty(home["file"]) and ".." not in Path(home["file"]).parts
             and home["file"].startswith("textual-notation-of-model/"),
             f"{identity}: home.file must be a governed model path")
    owner = home["owner"]
    _require(isinstance(owner, str) and (_DEF_OWNER.match(owner) or _PACKAGE_OWNER.match(owner)),
             f"{identity}: home.owner must be 'package X' or '<kind> def X'")
    if form in ("named-doc", "vocabulary-role", "retirement-record"):
        _require(isinstance(home["name"], str) and _IDENT.match(home["name"]) is not None,
                 f"{identity}: home.name must be an identifier")
    if form in ("owned-doc", "named-doc"):
        _require(isinstance(home["index"], int) and not isinstance(home["index"], bool)
                 and home["index"] >= 0, f"{identity}: home.index must be a non-negative integer")
    if form == "vocabulary-role":
        _require(_PACKAGE_OWNER.match(owner) is not None,
                 f"{identity}: a vocabulary-role comment must be package-owned")
        _require(home["name"].endswith("VocabularyRole"),
                 f"{identity}: vocabulary-role names end in VocabularyRole")
        about = home["about"]
        _require(isinstance(about, list) and about and all(isinstance(a, str) and _IDENT.match(a) for a in about)
                 and len(set(about)) == len(about), f"{identity}: home.about must list unique identifiers")
        imports = home["about_imports"]
        _require(isinstance(imports, dict) and set(imports) <= set(about) and all(
            _nonempty(path) and path.startswith("textual-notation-of-model/") and ".." not in Path(path).parts
            for path in imports.values()),
            f"{identity}: home.about_imports maps about targets to their defining governed model file")
    if form == "retirement-record":
        _require(home["file"] == SUCCESSOR_FILE and owner == f"package {SUCCESSOR_PACKAGE}",
                 f"{identity}: retirement records live in the relationship-successor package")


def _validate_gates(identity: str, row: dict[str, Any]) -> None:
    gates = row["gates"]
    _require(isinstance(gates, list), f"{identity}: gates must be a list")
    seen = set()
    for gate in gates:
        _require(isinstance(gate, dict) and set(gate) == {"gate", "resolved_by"},
                 f"{identity}: each gate carries exactly gate and resolved_by")
        _require(isinstance(gate["gate"], str) and re.fullmatch(r"decision-\d+|row-blocker", gate["gate"]) is not None,
                 f"{identity}: gate must be decision-N or row-blocker")
        _require(gate["gate"] not in seen, f"{identity}: duplicate gate {gate['gate']}")
        seen.add(gate["gate"])
        refs = gate["resolved_by"]
        _require(isinstance(refs, list) and refs and all(
            isinstance(ref, str) and re.fullmatch(r"docs/[A-Za-z0-9_./-]+\.(?:md|yaml)#[A-Za-z0-9_.-]+", ref)
            and ".." not in ref for ref in refs), f"{identity}: resolved_by must list docs/ record fragments")
    obligations = row["forward_obligations"]
    _require(isinstance(obligations, list) and all(_nonempty(item) for item in obligations),
             f"{identity}: forward_obligations must list non-empty strings")


def _validate_row(row: Any) -> str:
    _require(isinstance(row, dict), "admitted rows must be mappings")
    identity = row.get("identity")
    _require(isinstance(identity, str) and _IDENT.match(identity) is not None, "admitted row missing identity")
    kind = row.get("semantic_kind")
    _require(kind in SEMANTIC_KINDS, f"{identity}: semantic_kind must be class or relationship")
    admission = row.get("admission_class")
    _require(admission in ADMISSION_CLASSES, f"{identity}: unknown admission_class {admission!r}")
    expected_kind = ADMISSION_CLASSES[admission]
    _require(expected_kind in (None, kind), f"{identity}: admission_class {admission} requires {expected_kind}")
    allowed = _COMMON_KEYS | (_CLASS_KEYS if kind == "class" else _RELATIONSHIP_KEYS)
    extra = set(row) - allowed
    _require(not extra, f"{identity}: unknown keys {sorted(extra)}")
    missing = _COMMON_KEYS - set(row)
    _require(not missing, f"{identity}: missing keys {sorted(missing)}")
    register = row["register"]
    _require(isinstance(register, dict) and set(register) == {"wave", "accounting"}
             and register["accounting"] in ACCOUNTING
             and (register["wave"] is None or re.fullmatch(r"W[2-6]|closure", str(register["wave"]))),
             f"{identity}: register must carry wave and accounting")
    _require((register["wave"] is None) == (register["accounting"] != "retained"),
             f"{identity}: only retained rows carry a register wave")
    _require(row["boundary"] in BOUNDARIES, f"{identity}: unknown boundary")
    _validate_home(identity, row["home"])
    form = row["home"]["form"]
    reviewed = row["reviewed_definition"]
    if form in ("owned-doc", "named-doc"):
        _require(_nonempty(reviewed), f"{identity}: a documentation home needs the reviewed definition oracle")
    else:
        _require(reviewed is None, f"{identity}: {form} homes carry no authored definition")
    _validate_gates(identity, row)
    if kind == "class":
        _require(form in ("owned-doc", "named-doc"), f"{identity}: classes need a definition documentation home")
        grounding = row.get("grounding")
        _require(isinstance(grounding, dict) and set(grounding) == {"kernel_mapping", "sub_class_of", "disjoint_with"},
                 f"{identity}: grounding carries kernel_mapping, sub_class_of and disjoint_with")
        mapping = grounding["kernel_mapping"]
        _require(isinstance(mapping, dict) and (
            (set(mapping) == {"file", "declaration"} and all(_nonempty(mapping[k]) for k in mapping)
             and _DEF_OWNER.match(mapping["declaration"]) is not None)
            or (set(mapping) == {"native"} and _nonempty(mapping["native"]))
            or (set(mapping) == {"external"} and _nonempty(mapping["external"]))),
            f"{identity}: kernel_mapping must be exactly file+declaration, native or external")
        _require(grounding["sub_class_of"] is None or _IDENT.match(str(grounding["sub_class_of"])) is not None,
                 f"{identity}: sub_class_of must be an identity or null")
        disjoint = grounding["disjoint_with"]
        _require(isinstance(disjoint, list) and all(_IDENT.match(str(x)) for x in disjoint),
                 f"{identity}: disjoint_with must list identities")
    else:
        if admission != "successor":
            relation = row.get("relation")
            _require(isinstance(relation, dict) and set(relation) == {"domain", "range", "semantic_strength"}
                     and _IDENT.match(str(relation["domain"])) and _IDENT.match(str(relation["range"]))
                     and (relation["semantic_strength"] is None or _nonempty(relation["semantic_strength"])),
                     f"{identity}: relation carries domain, range and semantic_strength")
        else:
            _require("relation" not in row, f"{identity}: successor end pairs come from the model records")
    has = {key: key in row for key in ("mechanics", "range_discriminator", "successor", "alias", "external_reference", "carrier")}
    _require(has["successor"] == (admission == "successor"), f"{identity}: successor block iff admission_class successor")
    _require(has["alias"] == (admission == "deprecated-alias"), f"{identity}: alias block iff deprecated-alias")
    _require(form == "retirement-record" if admission == "deprecated-alias" else form != "retirement-record",
             f"{identity}: deprecated aliases (and only they) are homed by a retirement record")
    if admission == "relationship-runtime":
        _require(has["mechanics"], f"{identity}: runtime-mapped rows carry serializer mechanics")
    if has["mechanics"]:
        mechanics = row["mechanics"]
        _require(admission in ("relationship-runtime", "external-reference") and isinstance(mechanics, dict)
                 and _nonempty(mechanics.get("strategy")) and "semantic_strength" not in mechanics,
                 f"{identity}: mechanics need a strategy and no semantic_strength")
    if has["range_discriminator"]:
        disc = row["range_discriminator"]
        _require(isinstance(disc, dict) and set(disc) == {"kind", "lineage", "closure"} and disc["kind"] == "type-lineage",
                 f"{identity}: range_discriminator carries kind type-lineage, lineage and closure")
        for pin in [disc["lineage"], *disc["closure"]]:
            _require(isinstance(pin, dict) and set(pin) == {"file", "declaration"}
                     and _nonempty(pin["file"]) and _DEF_OWNER.match(str(pin["declaration"])) is not None,
                     f"{identity}: discriminator pins carry file and declaration")
        _require(len({(p["file"], p["declaration"]) for p in disc["closure"]}) == len(disc["closure"]) > 0,
                 f"{identity}: discriminator closure pins must be non-empty and unique")
    if has["external_reference"]:
        ref = row["external_reference"]
        _require(admission == "external-reference" and isinstance(ref, dict) and set(ref) == {"accepted_ref"}
                 and _nonempty(ref["accepted_ref"]), f"{identity}: external_reference carries accepted_ref")
    if admission == "external-reference":
        _require(row["boundary"] == "external-content", f"{identity}: external references keep the external-content boundary")
    if has["carrier"]:
        carrier = row["carrier"]
        _require(isinstance(carrier, dict) and set(carrier) == {"file", "declaration"}
                 and _nonempty(carrier["file"]) and str(carrier["declaration"]).startswith("connection def "),
                 f"{identity}: carrier carries file and a connection def declaration")
    if has["successor"]:
        successor = row["successor"]
        _require(isinstance(successor, dict) and set(successor) == {"records"}
                 and isinstance(successor["records"], list) and successor["records"]
                 and all(isinstance(r, str) and _IDENT.match(r) for r in successor["records"])
                 and len(set(successor["records"])) == len(successor["records"]),
                 f"{identity}: successor.records must list unique record usage names")
    if has["alias"]:
        alias = row["alias"]
        _require(isinstance(alias, dict) and set(alias) == {"successor", "successor_carrier", "direction", "answer_mode"}
                 and _IDENT.match(str(alias["successor"])) and _IDENT.match(str(alias["successor_carrier"]))
                 and alias["direction"] in ("forward", "inverse")
                 and alias["answer_mode"] in ("successor-facts", "documentation-only"),
                 f"{identity}: alias carries successor, successor_carrier, direction and answer_mode")
    if row["boundary"] == "ple-no-configurator-authority":
        _require(admission in ("definition", "relationship-vocabulary"),
                 f"{identity}: PLE configuration rows stay vocabulary-only")
    return identity


def load_admission(path: Path) -> dict[str, Any]:
    """Load and shape-lock the governed batch-2 admission document."""
    import yaml

    if not path.is_file():
        raise DefinitionBatch2Error(f"batch-2 admission document missing: {path}")
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    _require(isinstance(document, dict), f"batch-2 admission document malformed: {path}")
    _require(document.get("schema") == ADMISSION_SCHEMA,
             f"batch-2 admission schema must be {ADMISSION_SCHEMA}: {document.get('schema')!r}")
    _require(_nonempty(document.get("status")), "batch-2 admission status is required")
    admitted = document.get("admitted")
    _require(isinstance(admitted, list) and bool(admitted), "batch-2 admitted rows are required (non-empty list)")
    seen: set[str] = set()
    for row in admitted:
        identity = _validate_row(row)
        _require(identity not in seen, f"{identity}: duplicate admitted identity")
        seen.add(identity)
    exceptions = document.get("exceptions")
    _require(isinstance(exceptions, list), "batch-2 exceptions must be a list (owner-visible, may be empty)")
    for entry in exceptions:
        _require(isinstance(entry, dict) and set(entry) == {"identity", "accounting", "reason"}
                 and _IDENT.match(str(entry["identity"])) and _nonempty(entry["reason"])
                 and entry["accounting"] in ("retained", "unregistered", "merged", "removed"),
                 "each exception carries identity, accounting and a non-empty reason")
        _require(entry["identity"] not in seen, f"{entry['identity']}: an exception cannot also be admitted")
    return document


def load_document(root: Path) -> dict[str, Any]:
    return load_admission(root / ADMISSION_PATH)


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------


def _inventory():  # type: ignore[no-untyped-def]
    from de4sdv.semantic import authority_inventory

    return authority_inventory


class _Model:
    def __init__(self, root: Path) -> None:
        self.root = root
        self.files: dict[str, _Source] = {}
        self.used: set[str] = set()

    def source(self, relative: str) -> _Source:
        if relative not in self.files:
            path = self.root / relative
            if ".." in Path(relative).parts or not path.is_file():
                raise DefinitionBatch2Error(f"governed model file missing: {relative}")
            self.files[relative] = _Source(relative, path.read_text(encoding="utf-8"))
        return self.files[relative]


def _successor_records(model: _Model) -> dict[str, Any]:
    source = model.source(SUCCESSOR_FILE)
    package = source.owner_block(f"package {SUCCESSOR_PACKAGE}")
    relations = {
        name: source.record_fields(span, SUCCESSOR_RECORD_FIELDS, name)
        for name, span in source.direct_record_usages(package, "SuccessorRelationRecord").items()
    }
    retirements = {
        name: source.record_fields(span, RETIREMENT_RECORD_FIELDS, name)
        for name, span in source.direct_record_usages(package, "SuccessorRetirementRecord").items()
    }
    versions = [
        source.record_fields(span, VERSION_RECORD_FIELDS, name)
        for name, span in source.direct_record_usages(package, "SuccessorVersionRecord").items()
    ]
    _require(len(versions) == 1, f"{SUCCESSOR_FILE}: exactly one SuccessorVersionRecord usage is required")
    _require(versions[0]["version"] == SUCCESSOR_CONTRACT,
             f"{SUCCESSOR_FILE}: successor version must be {SUCCESSOR_CONTRACT}")
    return {"relations": relations, "retirements": retirements, "version": versions[0]}


def _definition_text(model: _Model, row: dict[str, Any]) -> tuple[dict[str, Any], str]:
    identity = row["identity"]
    home = row["home"]
    source = model.source(home["file"])
    block = source.owner_block(home["owner"])
    annotations = source.direct_annotations(block)
    form = home["form"]
    if form in ("owned-doc", "named-doc"):
        name = home.get("name")
        docs = [a for a in annotations if a["kind"] == "doc" and a["name"] == (name if form == "named-doc" else None)]
        _require(len(docs) > home["index"],
                 f"{identity}: {home['owner']} owns no {'named ' + name if name else 'anonymous'} documentation at index {home['index']}")
        body = clean_body(docs[home["index"]]["body"])
        normalize = _inventory().normalize_text
        observation = "normalized-exact" if normalize(body) == normalize(row["reviewed_definition"]) else "differs"
        _require(observation == "normalized-exact",
                 f"{identity}: model documentation and reviewed definition differ (batch 2 admits normalized-exact only)")
        witness = {"source_file": home["file"], "owner": home["owner"], "form": form,
                   "documentation_name": name, "documentation_index": home["index"]}
        return {"documentation": body, "documentation_witness": witness,
                "documentation_observation": observation}, form
    if form == "vocabulary-role":
        comments = [a for a in annotations if a["kind"] == "comment" and a["name"] == home["name"]]
        _require(len(comments) == 1, f"{identity}: {home['owner']} must own exactly one comment {home['name']}")
        comment = comments[0]
        _require(comment["about"] == home["about"],
                 f"{identity}: {home['name']} annotates {comment['about']} not {home['about']}")
        for target in comment["about"]:
            other = home["about_imports"].get(target)
            if other is None:
                _require(source.defines(target) or source.names_documentation(target),
                         f"{identity}: about target {target} is not a definition or named documentation of {home['file']}")
                continue
            # Cross-file target: defined in the named file's single top-level
            # package, which the home file imports directly (wildcard or exact).
            defining = model.source(other)
            model.used.add(other)
            _require(defining.defines(target), f"{identity}: about target {target} is not defined in {other}")
            packages = [m[1] for m in re.finditer(r"\bpackage\s+([A-Za-z_]\w*)(?=\s*\{)", defining.mask)
                        if defining.depth[m.start()] == 0]
            _require(len(packages) == 1, f"{identity}: {other} must own exactly one top-level package")
            _require(re.search(r"\bimport\s+" + re.escape(packages[0]) + r"::(?:" + re.escape(target) + r"|\*)\s*;",
                               source.mask) is not None,
                     f"{identity}: {home['file']} does not import {packages[0]} for about target {target}")
        body = clean_body(comment["body"])
        _require(bool(body), f"{identity}: {home['name']} has an empty body")
        witness = {"source_file": home["file"], "owner": home["owner"], "form": form,
                   "comment_name": home["name"], "about": list(home["about"]),
                   "about_imports": dict(sorted(home["about_imports"].items()))}
        return {"documentation": body, "documentation_witness": witness,
                "documentation_observation": "model-owned-vocabulary-role"}, form
    raise DefinitionBatch2Error(f"{identity}: unsupported text home {form}")


def _representation(row: dict[str, Any]) -> tuple[str, str]:
    home = row["home"]
    if row["home"]["form"] in ("vocabulary-role", "retirement-record"):
        return FORM_REPRESENTATION[home["form"]]
    owner = home["owner"]
    definition = _DEF_OWNER.match(owner)
    if definition:
        keyword = definition["kind"]
        _require(keyword in REPRESENTATION_CLASSES, f"{row['identity']}: unsupported declaration kind {keyword!r}")
        return REPRESENTATION_CLASSES[keyword], API_METACLASSES[keyword]
    return FORM_REPRESENTATION["package-doc"]


def _end_pair(model: _Model, record_name: str, record: dict[str, str]) -> dict[str, Any]:
    source = model.source(SUCCESSOR_FILE)
    carrier = f"connection def {record['carrier']}"
    ends = source.carrier_ends(carrier)
    return {
        "record": record_name,
        "carrier": {"source_file": SUCCESSOR_FILE, "declaration": carrier, "ends": ends},
        "mechanism": record["mechanism"],
        "semantic_strength": record["strength"],
        "source_class": record["sourceClass"],
        "target_class": record["targetClass"],
        "source_usage": record["sourceUsage"],
        "target_usage": record["targetUsage"],
        "inverse_navigation": record["inverse"] or None,
    }


def _external_profile(root: Path) -> dict[str, dict[str, Any]]:
    import yaml

    path = root / EXTERNAL_REFERENCE_PROFILE_PATH
    _require(path.is_file(), f"external-reference profile missing: {EXTERNAL_REFERENCE_PROFILE_PATH}")
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    entries = document.get("profile_entries") if isinstance(document, dict) else None
    _require(isinstance(entries, list), "external-reference profile has no profile_entries")
    return {str(entry.get("identity")): entry for entry in entries if isinstance(entry, dict)}


def _row_outputs(root: Path, model: _Model, row: dict[str, Any], successors: dict[str, Any],
                 external: dict[str, dict[str, Any]], inputs: set[str]) -> tuple[dict[str, Any], dict[str, Any]]:
    identity = row["identity"]
    admission = row["admission_class"]
    home = row["home"]
    inputs.add(home["file"])
    representation_class, metaclass = _representation(row)
    projection: dict[str, Any] = {
        "identity": identity,
        "semantic_kind": row["semantic_kind"],
        "admission_class": admission,
        "register_wave": row["register"]["wave"],
        "accounting": row["register"]["accounting"],
        "boundary": row["boundary"],
    }
    profile: dict[str, Any] = {
        "profile_identity": f"{PROFILE_SCHEMA}#{identity}",
        "for_concept": identity,
        "representation_class": representation_class,
        "binding_contract_echo": {"source_file": home["file"], "owner": home["owner"], "api_metaclass": metaclass},
        "witness_forms": [WITNESS_FORMS[home["form"]]],
    }
    if home["form"] == "retirement-record":
        retirement = successors["retirements"].get(home["name"])
        _require(retirement is not None, f"{identity}: retirement record {home['name']} not found")
        _require(retirement["predicate"] == identity,
                 f"{identity}: retirement record {home['name']} retires {retirement['predicate']}")
        projection["definition"] = {
            "documentation": retirement["reason"],
            "documentation_witness": {"source_file": home["file"], "owner": home["owner"],
                                      "form": "retirement-record", "record": home["name"]},
            "documentation_observation": "model-owned-retirement-record",
        }
    else:
        projection["definition"], _ = _definition_text(model, row)
    if row["semantic_kind"] == "class":
        grounding = row["grounding"]
        mapping = grounding["kernel_mapping"]
        if "file" in mapping:
            source = model.source(mapping["file"])
            source.owner_block(mapping["declaration"])
            inputs.add(mapping["file"])
            ground: dict[str, Any] = {"kernel_binding_contract": {"source_file": mapping["file"],
                                                                  "declaration": mapping["declaration"]}}
        elif "native" in mapping:
            ground = {"kernel_native": mapping["native"]}
        else:
            ground = {"kernel_external": mapping["external"]}
        ground["ontology_relations"] = {"sub_class_of": grounding["sub_class_of"],
                                        "disjoint_with": list(grounding["disjoint_with"])}
        ground["contract_source"] = (
            "kernel mapping kind and ontology relations: reviewed manifest fields "
            "(test-locked to the authored ontology); file mappings are resolved "
            "in the model by this generator"
        )
        projection["grounding"] = ground
    if admission == "successor":
        names = row["successor"]["records"]
        matching = sorted(name for name, record in successors["relations"].items() if record["predicate"] == identity)
        _require(matching == sorted(names),
                 f"{identity}: model successor records {matching} != manifest {sorted(names)}")
        pairs = [_end_pair(model, name, successors["relations"][name]) for name in names]
        inverses = sorted({pair["inverse_navigation"] for pair in pairs if pair["inverse_navigation"]})
        projection["successor"] = {
            "contract": SUCCESSOR_CONTRACT,
            "version_supersedes": successors["version"]["supersedes"],
            "end_pairs": pairs,
            "inverse_navigation": inverses,
            "contract_source": "model successor relation records and carrier ends (generator-extracted)",
        }
        profile["successor_mechanics"] = [
            {"record": pair["record"], "mechanism": pair["mechanism"],
             "carrier": pair["carrier"]["declaration"], "source_usage": pair["source_usage"],
             "target_usage": pair["target_usage"]}
            for pair in pairs
        ]
    elif row["semantic_kind"] == "relationship":
        relation = row["relation"]
        projection["relation"] = {
            "domain": {"ontology_class": relation["domain"]},
            "range": {"ontology_class": relation["range"]},
            "canonical_direction": f"{relation['domain']} -> {relation['range']}",
            "semantic_strength": relation["semantic_strength"],
            "contract_source": (
                "domain/range/strength: reviewed manifest fields (test-locked to "
                "the authored ontology); not a structural model witness"
            ),
        }
    if "carrier" in row:
        carrier = row["carrier"]
        source = model.source(carrier["file"])
        inputs.add(carrier["file"])
        projection["carrier"] = {"source_file": carrier["file"], "declaration": carrier["declaration"],
                                 "ends": source.carrier_ends(carrier["declaration"])}
    if "range_discriminator" in row:
        disc = row["range_discriminator"]
        lineage = disc["lineage"]
        model.source(lineage["file"]).owner_block(lineage["declaration"])
        inputs.add(lineage["file"])
        target = _DEF_OWNER.match(lineage["declaration"])["name"]  # type: ignore[index]
        for pin in disc["closure"]:
            source = model.source(pin["file"])
            inputs.add(pin["file"])
            _require(source.specializes(pin["declaration"], target),
                     f"{identity}: closure pin {pin['declaration']} does not specialize {target}")
            _require(re.search(r"\bimport\s+DE4SDV_MethodContext::(?:" + re.escape(target) + r"|\*)\s*;",
                               source.mask) is not None,
                     f"{identity}: {pin['file']} does not import the owning kernel package")
        projection["relation"]["range"]["discriminator"] = {
            "kind": "type-lineage",
            "lineage": {"source_file": lineage["file"], "declaration": lineage["declaration"]},
            "closure": [{"source_file": p["file"], "declaration": p["declaration"]} for p in disc["closure"]],
            "rule": (
                "a target is in range iff its definition is in the specialization "
                "closure of the kernel lineage declaration, resolved through the "
                "governed kernel mapping; never by name, prefix or membership heuristic"
            ),
        }
    if "mechanics" in row:
        profile["serializer_mechanics"] = dict(row["mechanics"])
        profile["mechanics_source"] = (
            "reviewed manifest field equal to the authored mapping (test-locked); "
            "Wave C retires the authored copy"
        )
    if admission == "deprecated-alias":
        alias = row["alias"]
        relations = successors["relations"]
        pairs = [r for r in relations.values() if r["predicate"] == alias["successor"]
                 and r["carrier"] == alias["successor_carrier"]]
        _require(len(pairs) == 1,
                 f"{identity}: successor {alias['successor']} has no unique record over {alias['successor_carrier']}")
        navigation = alias["successor"]
        if alias["direction"] == "inverse":
            _require(bool(pairs[0]["inverse"]), f"{identity}: inverse alias needs a successor inverse navigation")
            navigation = pairs[0]["inverse"]
        projection["alias"] = {
            "deprecated": True,
            "successor": alias["successor"],
            "successor_navigation": navigation,
            "successor_carrier": alias["successor_carrier"],
            "direction": alias["direction"],
            "answer_mode": alias["answer_mode"],
            "removal": "Wave C (with the authored ontology)",
            "rule": (
                "documented deprecated name: answers are the successor's facts over "
                "this carrier with the successor's meaning; the old signature and "
                "claim are never translated into the successor"
                if alias["answer_mode"] == "successor-facts" else
                "documented deprecated name only: no fact is answered under this "
                "name (the model retirement record refuses an alias reading); "
                "query the successor"
            ),
        }
        profile["alias_resolution"] = {"successor": alias["successor"], "navigation": navigation,
                                       "carrier": alias["successor_carrier"],
                                       "answer_mode": alias["answer_mode"]}
    if "external_reference" in row:
        entry = external.get(identity)
        _require(entry is not None, f"{identity}: not an entry of the accepted external-reference profile")
        _require(entry.get("accepted_ref") == row["external_reference"]["accepted_ref"],
                 f"{identity}: accepted_ref differs from the accepted external-reference profile")
        inputs.add(EXTERNAL_REFERENCE_PROFILE_PATH)
        profile["external_reference"] = {
            "profile": EXTERNAL_REFERENCE_PROFILE_PATH,
            "accepted_ref": entry["accepted_ref"],
            "representation_class": entry.get("representation_class"),
        }
    if row["boundary"] == "ple-no-configurator-authority":
        profile["configurator_authority"] = "none (external catalogue, ADR 0006; decision-9)"
    projection["support"] = SUPPORT[admission]
    projection["traversal"] = False
    projection["api_identity"] = "unclaimed"
    return projection, profile


def build_outputs(root: Path, document: dict[str, Any]) -> dict[str, Any]:
    model = _Model(root)
    successors = _successor_records(model)
    external = _external_profile(root) if any("external_reference" in r for r in document["admitted"]) else {}
    inputs: set[str] = {SUCCESSOR_FILE}
    # (cross-file about targets are added to model.used while rows are built)
    projection_rows = []
    profile_entries = []
    for row in document["admitted"]:
        projection, profile = _row_outputs(root, model, row, successors, external, inputs)
        projection_rows.append(projection)
        profile_entries.append(profile)
    inputs |= model.used
    projection_rows.sort(key=lambda item: item["identity"])
    profile_entries.sort(key=lambda item: item["for_concept"])
    exceptions = sorted(
        ({"identity": e["identity"], "accounting": e["accounting"], "reason": e["reason"]}
         for e in document["exceptions"]), key=lambda e: e["identity"])
    return {
        "admitted": sorted(row["identity"] for row in document["admitted"]),
        "projection_rows": projection_rows,
        "profile_entries": profile_entries,
        "exceptions": exceptions,
        "model_inputs": sorted(inputs),
    }


def collect_bound_inputs(root: Path, outputs: dict[str, Any]) -> dict[str, str]:
    from de4sdv.semantic.authority_inventory import file_digest

    paths = {ADMISSION_PATH, DESIGN_PATH, MODULE_PATH, GENERATOR_PATH,
             AUTHORITY_INVENTORY_PATH, PROJECTION_O2P_PATH, *outputs["model_inputs"]}
    bound: dict[str, str] = {}
    for relative in sorted(paths):
        _require((root / relative).is_file(), f"bound input missing: {relative}")
        bound[relative] = file_digest(root, relative)
    return bound


def build_artifact_pair(root: Path, *, source_revision: str) -> dict[str, Any]:
    from de4sdv.semantic.authority_inventory import InventoryError, verify_source_revision_contains_inputs

    document = load_document(root)
    outputs = build_outputs(root, document)
    bound_inputs = collect_bound_inputs(root, outputs)
    try:
        verify_source_revision_contains_inputs(root, source_revision, bound_inputs)
    except InventoryError as exc:
        raise DefinitionBatch2Error(str(exc)) from exc
    model_inputs = [path for path in outputs["model_inputs"] if path.startswith("textual-notation-of-model/")]
    binding = {
        "source_revision": source_revision,
        "source_revision_note": (
            "Git commit that contains every bound input byte-for-byte. The gate "
            "validates commit existence, ancestry of the checked-out revision, "
            "per-input content equality and the recorded content digests."
        ),
        "artifact_commit": None,
        "artifact_commit_note": "Unknowable at generation; left explicitly unclaimed.",
        "generation_software": {
            "program_inputs": [MODULE_PATH, GENERATOR_PATH, AUTHORITY_INVENTORY_PATH, PROJECTION_O2P_PATH],
            "note": (
                "The batch-2 module, the shared generator script, and the two shared "
                "modules executed at generation time (normalization, digests and "
                "revision containment; canonical JSON)."
            ),
        },
        "semantic_model_revision": {
            "model_inputs": model_inputs,
            "note": "The governed model files read by the generator, contained byte-for-byte in source_revision.",
        },
        "governance_inputs": {
            "admission_document": {"path": ADMISSION_PATH, "digest": bound_inputs[ADMISSION_PATH]},
            "design_record": {"path": DESIGN_PATH, "digest": bound_inputs[DESIGN_PATH]},
            "external_reference_profile": (
                {"path": EXTERNAL_REFERENCE_PROFILE_PATH, "digest": bound_inputs[EXTERNAL_REFERENCE_PROFILE_PATH]}
                if EXTERNAL_REFERENCE_PROFILE_PATH in bound_inputs else None
            ),
        },
        "api_binding": {"status": "unclaimed",
                        "note": "No SysML API element UUID is claimed; profile entries state representation mechanics only."},
        "bound_inputs": bound_inputs,
    }
    projection = {
        "schema": PROJECTION_SCHEMA,
        "status": "admitted",
        "warning": WARNING,
        "binding": binding,
        "scope": {
            "admission": "O4 definition-admission batch 2 (definition-admission-batch2.yaml)",
            "admitted": outputs["admitted"],
            "exceptions": outputs["exceptions"],
            "note": (
                "no frozen O3 identity and no identity of another generated layer "
                "is admitted; exceptions are owner-visible and never silently fall back"
            ),
        },
        "rows": outputs["projection_rows"],
    }
    profile = {
        "schema": PROFILE_SCHEMA,
        "status": "admitted",
        "warning": WARNING,
        "binding": binding,
        "entries": outputs["profile_entries"],
    }
    return {"projection": projection, "profile": profile}


def run_check_errors(root: Path) -> list[str]:
    """Fail-closed repository check for the batch-2 admissions and artifacts."""
    from de4sdv.semantic.authority_inventory import validate_source_binding
    from de4sdv.semantic.projection_o2p import canonical_json

    try:
        document = load_document(root)
        build_outputs(root, document)
    except DefinitionBatch2Error as exc:
        return [f"{ADMISSION_PATH}: {exc}"]
    missing = [rel for rel in (PROJECTION_PATH, PROFILE_PATH) if not (root / rel).is_file()]
    if missing:
        return [
            f"{rel}: batch-2 definition artifacts not generated yet; commit the "
            "admission inputs first, then run scripts/generate_definition_projection.py "
            "(two-commit source binding)"
            for rel in missing
        ]
    try:
        committed = json.loads((root / PROJECTION_PATH).read_text(encoding="utf-8"))
        binding = committed["binding"]
    except (KeyError, ValueError, TypeError) as exc:
        return [f"{PROJECTION_PATH}: cannot read binding for validation: {exc}"]
    binding_errors = validate_source_binding(root, binding)
    if binding_errors:
        return [f"{PROJECTION_PATH}: source-revision binding invalid: {error}" for error in binding_errors]
    try:
        artifacts = build_artifact_pair(root, source_revision=binding["source_revision"])
    except DefinitionBatch2Error as exc:
        return [f"batch-2 definition artifact generation failed: {exc}"]
    errors = []
    for key, relative in (("projection", PROJECTION_PATH), ("profile", PROFILE_PATH)):
        if canonical_json(artifacts[key]) != (root / relative).read_text(encoding="utf-8"):
            errors.append(f"{relative}: committed {key} differs from regeneration from current inputs (regenerate and commit)")
    return errors
