#!/usr/bin/env bash
# One-time server provisioning for sysml-api.de4sdv.org (Hetzner Ubuntu 24.04).
#
# Run ON THE SERVER as root:
#   bash deployment/scripts/provision-server.sh
#
# Idempotent: safe to re-run. Installs Docker, the compose network stack,
# and creates the secret env file. It does NOT start the stack (that is
# deploy.py's job, after a validated baseline import) and does NOT touch DNS.
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "run as root" >&2
  exit 1
fi

DEPLOY_DIR=${DEPLOY_DIR:-/srv/de4sdv}
ENV_FILE="$DEPLOY_DIR/sysml2-api.env"

echo "==> Installing Docker Engine + compose plugin"
if ! command -v docker >/dev/null; then
  curl -fsSL https://get.docker.com | sh
fi
systemctl enable --now docker

echo "==> Creating $DEPLOY_DIR"
install -d -m 0750 "$DEPLOY_DIR"
install -d -m 0750 "$DEPLOY_DIR/status"
install -d -m 0750 "$DEPLOY_DIR/artifacts"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "==> Generating secret env file $ENV_FILE"
  DB_PASSWORD=$(openssl rand -hex 24)
  PLAY_HTTP_SECRET_KEY=$(openssl rand -hex 32)
  ACME_EMAIL=${ACME_EMAIL:?set ACME_EMAIL, e.g. ACME_EMAIL=you@example.org bash provision-server.sh}
  cat > "$ENV_FILE" <<EOF
# Generated by provision-server.sh; chmod 600. Never commit.
DB_NAME=sysml2
DB_USER=sysml2api
DB_PASSWORD=$DB_PASSWORD
PLAY_HTTP_SECRET_KEY=$PLAY_HTTP_SECRET_KEY
ACME_EMAIL=$ACME_EMAIL
EOF
  chmod 600 "$ENV_FILE"
else
  echo "==> $ENV_FILE already exists; keeping existing secrets"
fi

echo "==> Firewall (ufw): allow 22/80/443 only"
if command -v ufw >/dev/null; then
  ufw --force reset >/dev/null
  ufw default deny incoming
  ufw default allow outgoing
  ufw allow 22/tcp
  ufw allow 80/tcp
  ufw allow 443/tcp
  ufw --force enable
  ufw status verbose
else
  echo "ufw not present; install ufw or configure nftables equivalent" >&2
  exit 1
fi

echo "==> Provisioning complete. Next: run deployment/scripts/deploy.py from CI or locally."
