#!/usr/bin/env bash
# One-time server provisioning for sysml-api.de4sdv.org (Hetzner Ubuntu 24.04).
#
# Run ON THE SERVER as root:
#   ACME_EMAIL=you@example.org bash deployment/scripts/provision-server.sh
#
# Idempotent: safe to re-run. Installs every host-side dependency the
# deployment needs, creates a dedicated deployment virtualenv with the exact
# pinned Python dependencies required by the existing DE4SDV importer
# (no system-Python mutation, no full dev environment), sets up Docker + the
# compose network stack, and creates the secret env file. It does NOT start
# the stack (that is deploy.py's job, after a validated baseline import) and
# does NOT touch DNS.
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "run as root" >&2
  exit 1
fi

DEPLOY_DIR=${DEPLOY_DIR:-/srv/de4sdv}
VENV_DIR="$DEPLOY_DIR/venv"
ENV_FILE="$DEPLOY_DIR/sysml2-api.env"

echo "==> Installing host packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq \
  ca-certificates curl git \
  python3 python3-venv \
  openssl ufw jq unzip

echo "==> Installing Docker Engine + compose plugin"
if ! command -v docker >/dev/null; then
  curl -fsSL https://get.docker.com | sh
fi
systemctl enable --now docker

echo "==> Creating $DEPLOY_DIR"
install -d -m 0750 "$DEPLOY_DIR"
install -d -m 0750 "$DEPLOY_DIR/status"
install -d -m 0750 "$DEPLOY_DIR/artifacts"

echo "==> Creating dedicated deployment virtualenv at $VENV_DIR"
# Ubuntu 24.04 ships Python 3.12; the DE4SDV importer targets the same
# runtime family used by the privileged workflow.
python3 -m venv "$VENV_DIR"
"$VENV_DIR/bin/pip" install --no-input --upgrade pip >/dev/null
# Exact pinned dependencies required by the existing importer
# (scripts/import_sysml_api_baseline.py) — nothing beyond that scope:
#   PyYAML       ontology contract loading (pinned by the privileged workflow)
"$VENV_DIR/bin/pip" install --no-input "PyYAML==6.0.2"

echo "==> Dependency sanity check"
"$VENV_DIR/bin/python" - <<'PY'
import sys
assert sys.version_info >= (3, 12), f"python too old: {sys.version}"
import yaml  # noqa: F401  (PyYAML==6.0.2 must import)
print("python", sys.version.split()[0], "+ PyYAML OK")
PY
"$VENV_DIR/bin/pip" check
command -v git >/dev/null
command -v docker >/dev/null
command -v ufw >/dev/null
command -v jq >/dev/null
command -v openssl >/dev/null
echo "all host dependencies present"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "==> Generating secret env file $ENV_FILE"
  DB_PASSWORD=$(openssl rand -hex 24)
  PLAY_HTTP_SECRET_KEY=$(openssl rand -hex 32)
  ACME_EMAIL=${ACME_EMAIL:?set ACME_EMAIL, e.g. ACME_EMAIL=you@example.org bash provision-server.sh}
  cat > "$ENV_FILE" <<EOF
# Generated by provision-server.sh; chmod 600. Never commit.
DB_NAME=sysml2
DB_USER=sysml2api
DB_PASSWORD=$DB_PASSWORD
PLAY_HTTP_SECRET_KEY=$PLAY_HTTP_SECRET_KEY
ACME_EMAIL=$ACME_EMAIL
EOF
  chmod 600 "$ENV_FILE"
else
  echo "==> $ENV_FILE already exists; keeping existing secrets"
fi

echo "==> Firewall (ufw): allow 22/80/443 tcp only (no UDP; HTTP/3 disabled)"
if command -v ufw >/dev/null; then
  ufw --force reset >/dev/null
  ufw default deny incoming
  ufw default allow outgoing
  ufw allow 22/tcp
  ufw allow 80/tcp
  ufw allow 443/tcp
  ufw --force enable
  ufw status verbose
else
  echo "ufw not present; install ufw or configure nftables equivalent" >&2
  exit 1
fi

echo "==> Provisioning complete. Deploy with:"
echo "    sudo DEPLOY_DIR=$DEPLOY_DIR $VENV_DIR/bin/python deployment/scripts/deploy.py \\"
echo "         --bundle-dir $DEPLOY_DIR/artifacts/incoming --repo $DEPLOY_DIR/DE4SDV"
